<?php

/**
 * @file
 * Demonstrates use of the Cron API in Drupal - hook_cron().
 */

/**
 * @defgroup cron_example Example: Cron
 * @ingroup custom
 * @{
 * Example using Cron API, including hook_cron() and @QueueWorker plugins
 *
 * This example is part of the Examples for Developers Project
 * which you can download and experiment with at
 * http://drupal.org/project/examples
 */

/**
 * Implements hook_cron().
 *
 * We implement hook_cron() to do "background" processing. It gets called every
 * time the Drupal cron runs. We then decide what has to happen in response.
 *
 * In this example, we log a message after the time given in the state value
 * 'cron_example.next_execution'. Then we update that variable to a time in the
 * future.
 */
function chmi_cron() {
  // We access our configuration.
  $cron_config = \Drupal::configFactory()->getEditable('chmi.settings');
  // Default to an hourly interval. Of course, cron has to be running at least
  // hourly for this to work.
  $interval = $cron_config->get('interval');
  $interval = !empty($interval) ? $interval : 3600;

  // We usually don't want to act every time cron runs (which could be every
  // minute) so keep a time for the next run in the site state.
  $next_execution = \Drupal::state()->get('chmi.next_execution');
  $next_execution = !empty($next_execution) ? $next_execution : 0;
  if (REQUEST_TIME >= $next_execution) {
    // This is a silly example of a cron job.
    // It just makes it obvious that the job has run without
    // making any changes to your database.
    \Drupal::logger('chmi')->notice('chmi ran');
    if (\Drupal::state()->get('chmi_show_status_message')) {
      drupal_set_message(t('chmi executed at %time', ['%time' => date_iso8601(REQUEST_TIME)]));
      \Drupal::state()->set('chmi_show_status_message', FALSE);
    }
    \Drupal::state()->set('chmi.next_execution', REQUEST_TIME + $interval);
  }
}
/**
 * Implements hook_theme().
 *
 */
function chmi_theme($existing, $type, $theme, $path)
{
return [
        'graph' => [
            'render element' => 'form',
        ],
    ];
}

function chmi_preprocess_page() {
    if (\Drupal::moduleHandler()->moduleExists('bootstrap_library')) {
        $library = theme_get_setting('bootstrap_barrio_library');
        switch ($library) {
            case 'cdn' :
                $variables['#attached']['library'][] = 'bootstrap_library/bootstrap-cdn';
                break;
            case 'production':
                $variables['#attached']['library'][] = 'bootstrap_library/bootstrap';
                break;
            case 'development':
                $variables['#attached']['library'][] = 'bootstrap_library/bootstrap-dev';
                break;
        }
    }
    else {
        $debug = 1;
    }
}
function chmi_page_attachments(array &$attachments) {
  // Unconditionally attach an asset to the page.
  $attachments['#attached']['library'][] = 'bootstrap_library/bootstrap';
}

function hook_page_attachments(array &$attachments) {
  // Unconditionally attach an asset to the page.
  $attachments['#attached']['library'][] = 'bootstrap_library/bootstrap';
}

/**
 * @} End of "defgroup cron_example".
 */
